### ISSUE TITLE
Doesn't support unicode very well.

### ISSUE THREAD

**Issue by Mm2PL** [tsoding/cm#139] opened 2020-07-28 19:40 UTC
![cmv22020-07-28_21-37](https://user-images.githubusercontent.com/25011746/88712803-d19f2480-d109-11ea-830f-d7a40a20ff81.png)

## How to reproduce
  1. run a command that returns unicode characters, 

## Example:
`printf π`
### Output
> PID: 1016281, Command: printf ~@
> ~@
> -- Execution Finished with status code: 0 --

### Expected output
> PID: 1016281, Command: printf π
> π
> -- Execution Finished with status code: 0 --

Note: this seems to happen when processing the output, not the input, since `cat`ing a file with unicodes still works

**Comment by rexim** [comment] 2020-09-15 12:20
@Mm2PL I tried to address this problem in #139. Please check it when you get a chance and close this issue if the problem is fixed for you.

**Comment by zhiayang** [comment] 2020-09-15 13:49
I haven't gotten around to testing it, but I suspect there might be issues with double-width characters (which is why i asked about emoji). From what I remember, it should suffice to calculate the length of the display line not by the number of characters, but by calling `wcwidth` (or something like that) on the string instead, and chopping/padding based on that length.

**Comment by rexim** [comment] 2020-09-21 12:35
@zhiayang if I understand you correctly (I already forgot the context of the discussion FeelsOldMan) I created a separate issue for that situation #189.

On top of that I think we are done with this specific issue and should finally close it. The case presented in the description works as expected. For everything else we can create separate issues.

What do you think?

**Comment by Mm2PL** [comment] 2020-09-21 12:46
Emoji don't work right. If you put a bunch of emoji in a regex, the editor will be offset to the right.
`regexs = 😂👌💯🔥 😂👌💯🔥😂👌💯🔥😂👌💯🔥😂👌💯🔥😂👌💯🔥😂👌💯🔥😂👌💯🔥😂👌💯🔥😂👌💯🔥😂👌💯🔥😂👌💯🔥😂👌💯🔥😂👌💯🔥😂👌💯🔥😂👌💯🔥😂👌💯🔥😂👌💯🔥`
Input/output of normal-width Unicode characters works correctly
![cm2020-09-21_14-45](https://user-images.githubusercontent.com/25011746/93768068-643eda00-fc08-11ea-9a5f-38ac30d28bc5.png)
The red line is about where the `emacs` setting should be.

**Comment by zhiayang** [comment] 2020-09-22 06:22
yep, i don't think this is about the regex highlighting, but rather just the general display width of double-width characters

**Closed** 2020-09-22 13:28 UTC

**Comment by rexim** [comment] 2020-09-22 13:29
@zhiayang @Mm2PL thank you so much for helping me to resolve this issue. The unicode is not supported "very well" as per issue title yet, but I'm gonna close this issue anyway. Let's open separate small scoped issues for the rest of the unicode related problems, okay?
